
return {
    /**
     * @namespace Fingerprint
     * @memberof quixot
     */
    Fingerprint: {
        /**
         *
         * @method data
         * @memberof quixot.Fingerprint
         * @returns {Object} the full scanned properties
         */
        data: fingerprint_data,
        /**
         *  @method identifier
         *  @memberof quixot.Fingerprint
         *  @returns {String} The unique fingerprint identifier
         */
        identifier: fingerprint_identifier,

        /**
         * @memberof quixot.Fingerprint
         * @method text
         * @returns {String} the text to compose the identifier
         */
        text: fingerprint_text,
        /**
         * @method numbers
         * @memberof quixot.Fingerprint
         * @returns {String} the numbers from text()
         */
        numbers: fingerprint_numbers
    },

    /**
     * @namespace Event
     * @memberof quixot
     */
    Event: {
        /**
         * the name of the event witch is triggered any time an "Event.appoint" is registered
         * @property {String}
         * @memberof quixot.Event
         */
        APPOINTMENT_DONE: 'quixot_event_appointment_done',
        /**
         * @method dispatch
         * @memberof quixot.Event
         * @param name {String} required
         * @returns {Number} -1 if error occurs, 0 if no event is registered, > 0 as length of
         *                   registered events for specified name
         */
        dispatch: event_dispatch,
        /**
         * check if a provided listener exist using declared or autogenerated "uidName" from "addListener"
         * @method hasListener
         * @memberof quixot.Event
         * @param eventName {String} required
         * @param uidName {String} optional, if provided when listener was added
         * @returns {Boolean} true if the listener exist
         */
        hasListener: hasEventListener,

        /**
         * register an event listener
         * @method addListener
         * @memberof quixot.Event
         * @param eventName {String} required
         * @param callback {Function} required
         * @param uidName {String} an optional unique identifier for the method,
         * to be used when removing the event handler
         * @example
         * quixot.addEventListener('whenMyJobIsCompleted', function(){
         *      console.log('finished');
         * }, 'myUniqeId');
         * @returns {Object} The current registered event listeners
         */
        addListener: addEventListener,

        /**
         * remove a registered event listener
         * @method removeListener
         * @memberof quixot.Event
         * @param eventName {String} name of the event to be removed
         * @param uidName {String} optional. If not provided default function to string will be used
         * @returns {boolean} true if the listener is removed, false if listener does not exist anymore
         */
        removeListener: removeEventListener,
        /**
         * retrieve all registered events and dispacthers
         * @method getAll
         * @memberof quixot.Event
         * @returns {Object}
         */
        getAll: getAllEvents,

        /**
         * appoint a method. If the environment is browser the appointment will be done via "requestAnimationFrame". <br />
         * For NodeJS, method "setImmediate" will be used, so the "id" property of the result will be an object.
         * @method appoint
         * @memberof quixot.Event
         * @param callback {Function} required
         * @param delay  {Number} optional, used only for setTimeout
         * @returns {Object} containing 2 properties: "type" => a string describing the used method for appointment (mozRequestAnimationFrame|setImmediate|setTimeout|nothing_found)
         * and an "id" => the data return by the method. <br /> This can be used as parameter for  "dropAppoint".
         */
        appoint: requestAnimationFrame,


        /**
         * cancel an appoint. Usage of this method should be avoided, since further changes on "appoint" method might
         * return undroppable callbacks.
         * @method dropAppoint
         * @memberof quixot.Event
         * @param id {Object|Number} required
         * @returns {Boolean} false if "id" is not provided or is invalud
         */
        dropAppoint: removeAnimationFrame
    },
    /**
     * @namespace URL
     * @memberof quixot
     */
    URL: {
        /**
         * retrieve the parameters from a given url
         * @method getParams
         * @memberof quixot.URL
         * @param url {String}
         * @returns {Object}
         * @example
         * quixot.URL.getParams("test.html?one=1&two=2")
         * //returns Object {one: 1, two: 2}
         * // same as:
         * quixot.URL.decode("test.html?one=1&two=2").params
         */
        getParams: url_get_params,
        /**
         * Extract the domain from an url.
         * @method getDomainFromUrl
         * @memberof quixot.URL
         * @param url {String}
         * @returns {String} For any invalid input, default return value is "localhost"
         * @example
         *      quixot.URL.getDomainFromUrl('https://www.mydomain.com/page?args=more');
         */
        getDomainFromUrl: url_getDomainFromUrl,
        /**
         * returns the current domain
         * @method currentDomain
         * @memberof quixot.URL
         * @returns {String} for NodeJS environment default value will be "localhost"
         * @example
         *      quixot.URL.currentDomain(); //produces the same result as:
         *      quixot.URL.getDomainFromUrl(document.URL)
         */
        currentDomain: url_currentDomain,
        /**
         * converts an object to a url query model. Inherited objects are converted into json string. <br />
         * Lists are converted into csv format
         * @method querify
         * @memberof quixot.URL
         * @param object {Object} object in json format
         * @returns {String}
         * @example
         * quixot.URL.querify({a:1, b:[1, 2, 3], g:"text", c:{d:2, f:"some string"}});
         * //output: 'a=1&b=[1,2,3]&g=text&c={"d":2,"f":"some string"}'
         */
        querify: url_querify,
        /**
         * @method decode
         * @memberof quixot.URL
         * @param url {String}
         * @returns {Object}
         * @example
         * quixot.URL.decode('http://mydomain/page1/page2/finalPage?arg0=1,2,3&arg1=[1,2,3]');
         * //protocol => 'http'
         * //lastPage => 'finalPage'
         * //parts[2] =>mydomain
         * //params.arg0[0] => '1'
         * //params.arg1[0] => '[1'
         */
        decode: url_decode,
        /**
         * cross browser support for window.location.pathname.
         * For non browsers environment, empty string is returned
         * @method currentPath
         * @memberof quixot.URL
         * @returns {String} current path name, as defined by window.location.pathname.
         */
        currentPath: url_current_path,
        /**
         * @method currentSearch
         * @memberof quixot.URL
         * @returns {String} current search name, as defined by window.location.search
         */
        currentSearch: url_current_search,
        /**
         *
         * @method currentParams
         * @memberof quixot.URL
         * @returns {Object} current url params
         * @example
         * quixot.URL.currentParams();  retrieve the same data as:
         * quixot.URL.decode(document.URL).params;
         */
        currentParams: url_current_params
    },

    /**
     * @namespace Logger
     * @memberof quixot
     * @example
     *   var myLogger = quixot.Logger.getInstance('TestLogger');
     *   myLogger.log('info', 'some message');
     *   myLogger.error('error occured');     //produces the same as
     *   myLogger.log('error', 'error occured');
     *   myLogger.info('info data');          //produces the same as
     *   myLogger.log('info', 'info data');
     *   quixot.Logger.warn('warning');        //produces the same as
     *   quixot.Logger.getInstance('quixot').log('warn', '111111');
     *   quixot.Logger.trace('bla-bla-bla');   ///produces the same as
     *   quixot.Logger.getInstance('quixot').log('warn', '111111');
     */
    Logger : {
            /**
             * @method info
             * @memberof quixot.Logger
             * @param message {Object}
             */
            info: function (message) {
                logger_defaultInstance.log('info', message);
            },
            /**
             * @method setDefaultConfig
             * @memberof quixot.Logger
             * @param config {Object}
             */
            setDefaultConfig: function(object) {
                for(var i in object) {
                    logger_defaultConfiguration[i] = object[i];
                }
            },
            /**
             * @method getDefaultConfig
             * @memberof quixot.Logger
             * @returns {Object} logger_defaultConfiguration
             */
            getDefaultConfig: function () {
                return logger_defaultConfiguration;
            },
            /**
             * @method trace
             * @memberof quixot.Logger
             * @param message {Object}
             */
            trace: function (message) {
                logger_defaultInstance.trace(message);
            },
            /**
             * @method error
             * @memberof quixot.Logger
             * @param message {Object}
             */
            error: function(message){
                logger_defaultInstance.log('error', message);
            },
            /**
             * @method warn
             * @memberof quixot.Logger
             * @param message {Object}
             */
            warn: function (message) {
                logger_defaultInstance.warn(message);
            },
            /**
             * @method getLogs
             * @memberof quixot.Logger
             * @returns {Object} default instance logs
             */
            getLogs: function () {
                return logger_defaultInstance.getLogs();
            },
            /**
             * @method getAll
             * @memberof quixot.Logger
             * @returns {Object} the logger_container with all logging instances
             */
            getAll: logger_getContainer,
            /**
             * returns a new logger instance
             * @method getInstance
             * @memberof quixot.Logger
             * @param instancename {String} required
             * @param config {Object} optional logger configuration
             * @returns {Object} the logger_container with all the logger instances
             * @example
             * var myLogger = quixot.Logger.getInstance('TestLogger');
             */
            getInstance: logger_getInstance,
            /**
             * set the value for accessing logger configuration from URL.
             * If is set to ``` false```, no configuartion can
             * be changed by using URL parameters
             * @method setURLAccessKey
             * @memberof quixot.Logger
             * @param name {String} required
             * @example
             * //this will allow you to put the following query param into url:
             * //http://localhost/mypage?customKey={"ALL":{"consoleAppender":true}}
             * quixot.Logger.setURLAccessKey('customKey');
             */
            setURLAccessKey: logger_setoptkey
    },
    /**
     * @namespace Cookie
     * @memberof quixot
     */
    Cookie: {
        /**
         * @method getc
         * @memberof quixot.Cookie
         * @param name {String}
         * @returns {String}
         */
        getc: getCookie,

        /**
         * create a new cookie
         * @method setc
         * @memberof quixot.Cookie
         * @param name {String}
         * @param value {String}
         * @param expires {Date|Number}
         * @param path {String}
         * @param domain {String}
         * @param secure {Boolean}
         * @returns {string}
         */
        setc: setCookie,

        /**
         * delete cookie
         * @method drop
         * @memberof quixot.Cookie
         * @param name {String}
         * @param path {String}
         * @param domain {String}
         * @returns {String} empty string
         */
        drop: deleteCookie
    },

    /**
     * @namespace Util
     * @memberof quixot
     */
    Util: {
        /**
         * encode any type of javascript data type (specially numbers) to string
         * @method atos
         * @memberof quixot.Util
         * @param data {Number|String|Date|Object|Array|Function} required
         * @param mapping {String} optional a string whose characters will be used for encoding
         * @param zval {Number} the value for 0, used for encoding duplicated numeric characters
         * @returns {String}
         * @example
         *  quixot.atos(123456789); // "mdefghij"
         *  quixot.atos(000000); // "a"
         *  quixot.atos('000000'); // "abcdef"
         *  quixot.atos('000000', '!@#$%^&*()+='); // "!@#$%^"
         */
        atos: util_atos,

        /**
         * converts any type of data into a string containing only numeric characters
         * @method aton
         * @memberOf quixot.Util
         * @param input {String|Number|Array|Object|Date}
         * @param separator {String} a separator for numbers
         * @returns {String} a string containing only numeric characters
         * @example
         *  quixot.Util.aton('\""', '__'); // "54__54"
         *  quixot.Util.aton(1234+'bcd'); //"1234234"
         */
        aton: util_aton,
        /**
         * generates an unique id that begins with a letter ([A-Za-z])
         * and may be followed by any number of letters, digits ([0-9])
         * @method makeDomId
         * @memberOf quixot.Util
         * @param prefix {String} optional, a prefix to be appended at the begging of the string
         * @returns {String}
         */
        makeDomId: util_dom_id,
        stringToHex: util_stringToHex,
        rgbToHex: util_rgbToHex,
        rgbToHexShift: util_rgbToHexShift,
        serialize: util_serialize,
        simplify: util_simplify,
        isPrimitive: util_isPrimitive,
        isFunction: util_isFunction,
        util_objKeys: util_objKeys,
        isArray: util_isArray,
        encodeObject: util_encodeObject,
        stringify: util_stringify,
        /**
         * increments an unique number (old value is cached)
         * @memberof quixot.Util
         * @param asfloat {Boolean} optional
         * @returns {Number} positive integer
         * @example
         * quixot.Util.incr(true); // 30.07000000000001
         * quixot.Util.incr();    // 31
         */
        incr: util_incr,
        /**
         * if no parameters are provided a quixot.Util.incr() value will be returned
         * @memberof quixot.Util
         * @param min limit range if "max" is not provided
         * @param max limit range
         * @returns {Number} as float
         * @example
         * quixot.Util.randNr(3); // will generate numbers betwen 0 and 3, like 0.6573690931544247
         * quixot.Util.randNr(2, 4); // will generate numbers betwen 2 and 4, like 2.3124963172024833
         * quixot.Util.randNr(-5); // will generate numbers betwen -5 and 0, like -4.3664502906423195
         */
        randNr: function (min, max) {}
    },
    /**
     * supports browser && nodejs
     * @module Cache
     * @namespace Cache
     * @memberof quixot
     */
    Cache: {
            getInstance: getCacheInstance,

            /**
             * put item in cache
             * @function
             * @memberof quixot.Cache
             * @param key {String}
             * @param value {String|Number}
             */
            put: function (key, value) {
                domainCacheInstance.put(key, value)
            },

            remove: function (key) {
                domainCacheInstance.remove(key);
            },

            getData: function () {
                return  domainCacheInstance.getData()
            },

            getSafe: function (propname, defaultvalue) {
                return  domainCacheInstance.getSafe(propname, defaultvalue)
            }
    },
    /**
     * contains data related to enviroment:
     * @namespace Env
     * @memberof quixot
     * @example
     * quixot.Env.jsEngine.isBrowser; //true if script is running in browser
     * quixot.Env.jsEngine.isNodeJs;  //true if script is running in node js
     * quixot.Env.javaEnabled;        //true if java is enabled in browser,
     *                                             // or if a path to JAVA_HOME exist is operating system enviroment
     * quixot.Env.tempDir             //path to operating system temporary directory
     * quixot.Env.homeDir             //path to operating system user home directory
     * quixot.Env.javaPath            //path to java binary (java.exe || java)
     */
    Env: envData,

    /**
     * system information (browser|nodejs)
     * @namespace System
     * @memberof quixot
     */
    System: {

        battery: system_battery,
        screen: screen_info,
        performance: system_getPerformance,

        /**
         * operating system info
         * @memberof quixot.System
         * @namespace os
         * @example
         * quixot.System.os.name; // returns the operating system generic name
                                  // nodejs support is provided via os.type if exists otherwise via
                                  // os.platform. Result may be "Windows|Mac|Linux"
           quixot.System.version  // returns operatinng system version
                                  // result may vary based on scanned features
                                  // browsers will return data based on user agent, nodejs
                                  // or other engines may provide content via 'os.release'
         */
        os: os_info
    },


    /**
     *  browser information< br/>
     *  @namespace Browser
     *  @memberof quixot
     *  @example
     *  quixot.Browser.name; (Chrome|Firefox|Explorer|Opera|iCab|rekonq|Midori|Arora|Stainless|Epiphany|K-Meleon|Camino|Maxthon|SeaMonkey|Edge|OmniWeb|Apple|KDE|Netscape|MSIE|Gecko|Mozilla|Tizen)
     *  quixot.Browser.version;
     */
    Browser: {
        name: browserName,
        version: browserVersion,
        searchedData: browser_searched_data,
        is: getIs(),
        has: getHases(),
        get: getGeetters()
    },

    /**
     * the unit testing namespace
     * @namespace Sancho
     * @memberof quixot
     */
    Sancho : {
         equals: equals,
         deepEquals: deepEquals,
         hasData: hasData,
         donkey: monkey,
         config: testingCfg
    },

    Tween: Tween,
    Easing: Easing,

    /**
     * minimal graphic user interface components
     * designed to run inside any type of enviroment and provide if possible
     * native behaviour on visual components
     * @namespace Mingui
     * @memberof quixot
     */
    Mingui: {
        /**
         * for browsers the notify action will first try create a native html5 notification
         * if domain protocol is "http" or "https". <br /> Second second approach will
         * be to create a pop-up window. Please remember that second tryout will also
         * apply if user native notifications are blocked from settings.<br />
         * Finally, if the pop-up window is blocked, a simple html notification will
         * be added to current document, styled by default with operating system colors. <br />
         *
         * For nodejs enviroments
         * if java path is detected a spawned process wil start. (required java 1.8, this feature is still under developpement)
         * @function
         * @memberof quixot.Mingui
         * @param title {String}
         * @param text {String}
         * @param picture {String}
         * @param lifetime {Number}
         * @param success {Function}
         * @param failure {Function} although the method returns false due to known reasons, this callback is safe
         *                           to use. For example, native html5 notification require user approval. In this case
         *                           method will return false, but if user press "Allow" the "failure" callback
         *                           will never be called
         * @param onclick {Function} Attention!!! This callback may run without context in some implementations.
         * @param onclose {Function} Attention!!! This callback may run without context in some implementations.
         * @returns {Boolean|Object} false if notification fails to be displayed due to known reasons, an object with "remove()" method.
         */
        notify: cross_notify
    },

    Http: {
        request: http_request,
        doGet:http_get,
        doPost: http_post,
        doPostXForm: http_post_x_form
    },

    /**
     * Time utils
     * @namespace Time
     * @memberof quixot
     */
    Time: {
        interval: time_interval,
        dateAdd: time_date_add,
        dateRoll: time_date_roll
    },
    GOG: gog_root,

    /**
     * Dulcineea - a legacy code friendly MVC
     * @namespace Dulcineea
     * @memberof quixot
     */
    Dulcineea: {
        compiler: {
            execute: _execute_js,
            extract: extract_callers
        },
        templateRender : template_replace
    },
    /**
     * require safe support: cached node js requirements <br />
     * TODO support for http://requirejs.org/
     * @memberof quixot
     */
    require: __require,
    packInfo: quixot_pack_info,
    debug: {
        atos_memodata: function () {
            return util_atos_memodata;
        },
        wGL: function () {
            return  webGL;
        }
    }


}

})();



if(typeof module !='undefined') {
  module.exports = quixot;
}